# Generated by Django 2.1.8 on 2020-09-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200902_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detgle',
            old_name='movie',
            new_name='review',
        ),
    ]
