# Generated by Django 2.1.8 on 2020-09-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20200902_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='spo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
