# Generated by Django 2.1.8 on 2020-09-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20200902_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='read_cnt',
            field=models.IntegerField(default=0, verbose_name='READ_CNT'),
        ),
        migrations.AlterField(
            model_name='review',
            name='spo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
