# Generated by Django 2.1.8 on 2020-09-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20200903_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAttachFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('content_type', models.CharField(max_length=128, null=True, verbose_name='MIME TYPE')),
                ('size', models.IntegerField(verbose_name='파일 크기')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='SNImg',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='reviewattachfile',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='review.Review', verbose_name='Review'),
        ),
    ]
